### ISSUE TITLE
FeedBack来啦，关于背景

### ISSUE THREAD

**Issue by ForrestAlfred** [MoZhouqi/KMNavigationBarTransition#10]
设置了这个属性（navigationBar.backgroundColor）以后，会出Bug.
如图是我在 Demo 的 MainViewController 的 ViewDidLoad 加入以下代码的结果

     navigationController?.navigationBar.backgroundColor = UIColor.yellowColor()

![img_0186](https://cloud.githubusercontent.com/assets/8122371/13770459/1c2fe21a-eac2-11e5-8f07-90b905ea59c3.PNG)

![img_0187](https://cloud.githubusercontent.com/assets/8122371/13770460/1c88da00-eac2-11e5-8e40-128d4dfde0d4.PNG)

**Comment by ForrestAlfred** [comment]
又可以升级到 0.0.5 版本了：），期待ing ：)

**Comment by MoZhouqi** [comment]
哈哈哈，避免设置这个属性吧，感觉这个库不太适合去处理。

**Comment by MoZhouqi** [comment]
满足你了，已升 0.0.5，哈哈。

**Comment by ForrestAlfred** [comment]
0.0.5..... d
