### ISSUE TITLE
主题相关的bug

### ISSUE THREAD

**Issue by Rannie** [MoZhouqi/KMNavigationBarTransition#100]
比如我的应用支持换肤，那么 push 到那个页面之后 修改主题 pop 的时候 前一个页面 fake 的 navibar 还是之前的颜色，而且 viewDidAppear 之后也会把那个 navi 的颜色改回之前的颜色。

**Comment by MoZhouqi** [comment]
这种情况可能你需要直接去修改 fake bar 的背景色了。
