### ISSUE TITLE
自定义导航栏做按钮，出现手势返回无效

### ISSUE THREAD

**Issue by TML007** [MoZhouqi/KMNavigationBarTransition#106]
navigationController?.navigationBar.setBackgroundImage(#imageLiteral(resourceName: "nav_bg").withColor(#colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)), for: .default)
        navigationController?.navigationBar.shadowImage = UIImage()
        navigationItem.leftBarButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "nav_back_black").withRenderingMode(.alwaysOriginal), style: .done, target: self, action: #selector(backAction))

**Comment by gaoshanyu** [comment]
加代码：
`navigationController?.interactivePopGestureRecognizer!.delegate = self`

实现UIGestureRecognizerDelegate代理方法：
```
// UIGestureRecognizerDelegate
    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer == navigationController?.interactivePopGestureRecognizer {
            return navigationController!.viewControllers.count > 1
        }
        return true
    }
```
手势就可以用了

**Comment by MoZhouqi** [comment]
@gaoshanyu 正解，感谢回复。
