### ISSUE TITLE
导航栏背景颜色会闪一下

### ISSUE THREAD

**Issue by Jonzzs** [MoZhouqi/KMNavigationBarTransition#107]
为什么我遇到的和你说的已知问题是反的，使用 `setBarTintColor` 设置背景颜色不会出现闪一下的问题，使用 `setBackgroundImage: forBarMetrics:` 方法设置背景颜色，每次 `push` 一个页面，导航栏背景都会轻微的闪一下，以上情况都发生在 `translucent` 为 `YES` 的时候，`translucent` 为 `NO` 的时候不会有上述问题，但是页面会整体下移一个导航栏的高度，求解决办法...

**Comment by iostalks** [comment]
跳转的导航栏颜色一样吗？我这边没问题的哎，我是设置图片作为背景，会自动下移导航栏高度，设置个不透明度就好了

**Comment by zhouxiangzhong** [comment]
我这里有类似的问题，查代码发现UINavigationController+KMNavigationBarTransition.m第98行有一个代码，当animated==YES时，设置了km_backgroundViewHidden=YES，导致导航条隐藏。

我的页面逻辑：ViewControllerA是RN实现的，设置NavigationBar隐藏，在RN上做了一个假的NavigationBar(普通UIView)，由ViewControllerA视图控制器push到ViewControllerB视图控制器，ViewControllerB正常显示NavigationBar，问题在于：当从ViewControllerB视图控制器pop到ViewControllerA时，ViewControllerB的NavigationBar不显示，会闪现一个黑色块。

**Comment by EwanJJ** [comment]
更新xcode9所导致的吗?我也有类似的问题,定位了很久才发现是KM的原因,木有解决,选择弃用了

**Comment by MoZhouqi** [comment]
@zhouxiangzhong km_backgroundViewHidden 是隐藏了系统导航栏负责显示导航栏背景色的 view，然后会给 fromVC 和 toVC 加上 fake bar。

请问你导航栏隐藏的逻辑是怎么写的呢，README 里有关于隐藏导航栏的推荐方法。
```swift
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    navigationController?.setNavigationBarHidden(hidden, animated: animated)
}
```

**Comment by MoZhouqi** [comment]
@Jonzzs 能给个最小 demo 让我调试下吗，`translucent` 为 `NO` 导致页面下移是系统的行为，所以 README 里建议导航栏 `translucent` 属性设置好后最好就不要随意改动了。

**Comment by MoZhouqi** [comment]
@EwanJJ 能提供个最小 demo 吗。
