### ISSUE TITLE
pop回来Item被遮盖- KMNavigationBarTransition:  1.1.5

### ISSUE THREAD

**Issue by yanmingLiu** [MoZhouqi/KMNavigationBarTransition#115]
<img width="370" alt="qq20180223-145207 2x" src="https://user-images.githubusercontent.com/19849661/36582252-ad66a8b8-18ab-11e8-90ef-6e063ef7af45.png">

**Comment by MoZhouqi** [comment]
你好，我用 Xcode 自带的可视化工具看了下 pop 回来后，button 的 alpha 的值变成了 0.2，这个应该是系统的行为，不是 KMNavigationBarTransition 修改的。
