### ISSUE TITLE
iOS 11.2.6 Standard NavBar Transition Broken

### ISSUE THREAD

**Issue by jwardle** [MoZhouqi/KMNavigationBarTransition#120]
Hi, 

The transition to & from a clear navigation bar and a solid navigation bar works great. However when navigating between 2 VCs on using a standard NavigationController (Swift 4) it appears KMNavigationBarTransition may be overworking when not necessary & interfering with the transition creating a shadow effect under the status bar and VC content, but not the NavigationBar itself. 

See screenshot below to illustrate (mid-transition):
![img_1082](https://user-images.githubusercontent.com/2844831/37372839-236307fa-270c-11e8-81de-26edfa4b8aba.jpg)

As you can see towards the left hand side the navigation bar is solid across the 2 VCs involved in the transition, however there is also a shadow above and below the top VC elsewhere.

**Comment by jwardle** [comment]
Any suggestions on this?

**Comment by MoZhouqi** [comment]
Hi @jwardle, thanks for your feedback, could you please give me a demo to reproduce the problem?
