### ISSUE TITLE
iOS8下不能使用系统自带的右滑返回

### ISSUE THREAD

**Issue by crespoxiao** [MoZhouqi/KMNavigationBarTransition#14]
你好，我的工程中导入了KMNavigationBarTransition之后在iOS9上使用可以右滑返回，但是iOS8的模拟器上不可以，去掉KMNavigationBarTransition之后在iOS8上就可以右滑返回了。

**Comment by MoZhouqi** [comment]
有点诡异，按理说这个库不会对系统的边缘右滑返回有影响，而且我目前好几个 app 试下来也没发现这样的情况，你能拆一个 demo 出来让我试下吗？

**Comment by crespoxiao** [comment]
奇怪了，今天不能重现这个问题了。。。
我就是自定义了一个navigationcontroller，实现了一个协议。

`- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item{
 
    DLog(@"[self.viewControllers count]:%d [navigationBar.items count]:%d",[self.viewControllers count],[navigationBar.items count]);
    
    if([self.viewControllers count] < [navigationBar.items count]) {
        return YES;
    }

    UIViewController *vc = self.topViewController;
    if ([vc respondsToSelector:@selector(controllerWillPopHandler)]){
        if (![vc performSelector:@selector(controllerWillPopHandler)]){
            //!make sure the back indicator view alpha back to 1
            [[self.navigationBar subviews] lastObject].alpha = 1;
            return NO;
        }
    }
    
    [self popViewControllerAnimated:YES];
    return NO;
}`


先关掉这个issue，下次再说。
