### ISSUE TITLE
切换VC的过渡背景有问题

### ISSUE THREAD

**Issue by lexiaoyao20** [MoZhouqi/KMNavigationBarTransition#15]
如题，我从一个有NavigationBar的VC过渡到一个无NavigationBar背景有问题，如图：
![aaaa.gif](https://github.com/lexiaoyao20/TestNavigationBar/blob/master/ScreenShot/aaaa.gif)

这里是Demo地址：[https://github.com/lexiaoyao20/TestNavigationBar](https://github.com/lexiaoyao20/TestNavigationBar)

不知道是不是我哪里写得不对，麻烦大神有时间看一下

**Comment by MoZhouqi** [comment]
因为 `NextViewController` 的 `view` 的背景色是透明的，在 `NextViewController` 的 `viewDidLoad` 里加一句 `self.view.backgroundColor = [UIColor whiteColor];` 应该就行了。
