### ISSUE TITLE
导航栏透明度无效

### ISSUE THREAD

**Issue by ameue** [MoZhouqi/KMNavigationBarTransition#150]
使用tabbar，每个tabbar的controller创建UINavigationController，
BaseViewController的Viewdidload是这样配置的
self.edgesForExtendedLayout = UIRectEdgeNone;

    self.navigationController.navigationBar.translucent = NO;
    
    [self.navigationController.navigationBar setTitleTextAttributes:@{NSForegroundColorAttributeName : [UIColor blackColor]}];
    [self.navigationController.navigationBar setTintColor:[UIColor blackColor]];
    
    [self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:[UIColor whiteColor]] forBarMetrics:UIBarMetricsDefault];//默认导航栏背景白色
    self.navigationController.navigationBar.shadowImage = [UIImage imageWithColor:HexColor(0XEEEEEE)];//默认所有页面都有这一条线。
情景1
第一个tab1，第一页controller1不修改透明度，导航栏背景白色，导航栏底部的线条不处理，然后push controller2，在controller2中的viewWillAppear中添加

```
[self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
[self.navigationController.navigationBar setShadowImage:[UIImage new]];
```
情景2
tab2的根控制器controller3的viewWillAppear中添加：
```
[self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
[self.navigationController.navigationBar setShadowImage:[UIImage new]];
```
viewWillDisappear添加
```
[self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:[UIColor whiteColor]] forBarMetrics:UIBarMetricsDefault];
self.navigationController.navigationBar.shadowImage = [UIImage imageWithColor:HexColor(0XEEEEEE)];
```
controller2和controller3中都有self.edgesForExtendedLayout = UIRectEdgeAll;
出现的结果，
情景1：导航栏背景色透明无效。
情景2：如果controller3不继承baseController，controller3的导航栏能透明，进入下页面再返回的时候，导航栏透明不生效了。
            如果controller3继承basecontroller，controller3的导航栏透明不生效

**Comment by CoderLGL** [comment]
我的也是同样的问题，把下面这句话去掉就好了
self.edgesForExtendedLayout = UIRectEdgeNone;
