### ISSUE TITLE
iOS 14 适配问题

### ISSUE THREAD

**Issue by Weang** [MoZhouqi/KMNavigationBarTransition#155]
在 iOS 14 beta中更改导航栏颜色之后，页面跳转时不起作用

**Comment by oui123** [comment]
转场时用了假UINavigationBar的都这样 https://github.com/Tencent/QMUI_iOS/issues/1081

**Comment by Liaoworking** [comment]
same issue here

**Comment by wangkunzhen** [comment]
有支持iOS 14的计划吗？

**Comment by MoZhouqi** [comment]
@Liaoworking 感谢 pr，不过我试了下通过 xib 初始化也可以解决这个问题 8e4d445da0bba0e247255a1ed62cdf44fdc34be4，感觉这样 hack 比较小。

**Comment by MoZhouqi** [comment]
@Liaoworking 感谢 pr，不过我试了下通过 xib 初始化也可以解决这个问题 8e4d445，感觉这样处理 hack 比较小。

**Comment by Liaoworking** [comment]
> @Liaoworking 感谢 pr，不过我试了下通过 xib 初始化也可以解决这个问题 8e4d445，感觉这样处理 hack 比较小。

我写的时候也瑟瑟发抖哈哈，测了很久感觉应该问题不大，不过你这个要稳很多。

**Comment by MoZhouqi** [comment]
> > @Liaoworking 感谢 pr，不过我试了下通过 xib 初始化也可以解决这个问题 [8e4d445](https://github.com/MoZhouqi/KMNavigationBarTransition/commit/8e4d445da0bba0e247255a1ed62cdf44fdc34be4)，感觉这样处理 hack 比较小。
> 
> 我写的时候也瑟瑟发抖哈哈，测了很久感觉应该问题不大，不过你这个要稳很多。

pr 我已经合了，因为纯代码性能要比 xib 好。

**Comment by MoZhouqi** [comment]
@Weang @wangkunzhen 在 release 1.1.6 修复了这个问题。

**Comment by Liaoworking** [comment]
> @Weang @wangkunzhen 在 release 1.1.6 修复了这个问题。

我早上权衡了一下，我提的pr也只是暂时的解决方案，觉得xib的生成方式几乎没啥风险，要比我这个hack的方式稳很多，可能以后苹果改了私有api会导致其他问题。针对于性能方面， 早上在低端机iPhone6上for循环了5000次纯代码和xib的navigation bar的生成方式    得到的结论是 xib总共耗时 6.261s  纯代码耗时2.723s。   xib耗时为纯代码的两倍多， 再加上大部分机型性能是高于iPhone6的  其实用户在性能上几乎是无感知的。   在你提出xib的解决方案后觉得的确要比我这种好太多。

**Comment by MoZhouqi** [comment]
@Liaoworking 确实 xib 初始化的方式风险比较小，你之前的 pr 我回滚了，新的更改 9b23d106365252728a9dcef9bd3bdf5220e9e317，release 1.1.7

**Comment by Liaoworking** [comment]
> @Liaoworking 确实 xib 初始化的方式风险比较小，你之前的 pr 我回滚了，新的更改 [9b23d10](https://github.com/MoZhouqi/KMNavigationBarTransition/commit/9b23d106365252728a9dcef9bd3bdf5220e9e317)，release 1.1.7

好的！ 辛苦大兄弟了！  赶紧休息一下。

**Comment by MoZhouqi** [comment]
> > @Liaoworking 确实 xib 初始化的方式风险比较小，你之前的 pr 我回滚了，新的更改 [9b23d10](https://github.com/MoZhouqi/KMNavigationBarTransition/commit/9b23d106365252728a9dcef9bd3bdf5220e9e317)，release 1.1.7
> 
> 好的！ 辛苦大兄弟了！ 赶紧休息一下。

好的老铁，您也辛苦了！

**Comment by MoZhouqi** [comment]
我仔细研究了下，这个应该是苹果 bug，已经在 release 1.1.8 修复了，这次改动影响面非常小，应该是最终版了。
