### ISSUE TITLE
真级se ,iOS  12.4  播放器切换横屏，在动画的时候会崩溃， 其他机型包括模拟器都不会

### ISSUE THREAD

**Issue by qianga3** [MoZhouqi/KMNavigationBarTransition#156]

**Comment by qianga3** [comment]
![1599550214572_5B1CB6E0-1B78-425D-928A-D1F6BEC2D98D](https://user-images.githubusercontent.com/21187664/92446617-a7508480-f1e8-11ea-87f4-c38aa80a6c61.png)

**Comment by MoZhouqi** [comment]
为啥挂在了子线程呢？
