### ISSUE TITLE
Can't seem to get it to work with Objective-C Project

### ISSUE THREAD

**Issue by inb4ohnoes** [MoZhouqi/KMNavigationBarTransition#16]
I dropped the KMNavigationBarTransition folder into my project, and am not having success pushing a UITableView with translucent UINavigationBar with blank background image and blank shadow image onto a previous UITableView with regular UINavigationBar.

My view hierarchy is: UITabBarController -> UINavigationController subclass -> UIViewController. I have set both the background image and the shadow image of the navigation bar to [UIImage new] in the second view's `viewDidLoad:`. However, for some reason the navigation bar is not going away. Do you have any suggestions I could try? Thanks.

**Comment by inb4ohnoes** [comment]
I fixed it. It turns out I just had to move things into `viewWillAppear:` in my particular case.

**Comment by MoZhouqi** [comment]
Hi, could you give me a demo to find out why it is not effective to set in `viewDidLoad`?

**Comment by inb4ohnoes** [comment]
I'm actually quite confused myself. As far as I can tell, there is no reason the code should be in 'viewWillAppear'. When I say "move things" I mean only the two lines for setting the navbar background and line to blank images.
