### ISSUE TITLE
iOS15如何适配?

### ISSUE THREAD

**Issue by Wanglw2015** [MoZhouqi/KMNavigationBarTransition#167]

**Comment by waitingyip384031523** [comment]
初始化

**Comment by waitingyip384031523** [comment]
UIViewController+KMNavigationBarTransition.m中添加

**Comment by waitingyip384031523** [comment]
这是我的解决方案
1、初始化
if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *appearance = [UINavigationBarAppearance new];
        appearance.shadowColor = nil;
        appearance.shadowImage = [UIImage getImageWithColor:clear_color andSize:CGSizeMake(1, 1)];
        appearance.backgroundColor = nil;
        appearance.backgroundImage = [UIImage imageWithColor:clear_color];
        appearance.backgroundEffect = nil;
        appearance.titleTextAttributes = @{NSForegroundColorAttributeName:clear_color};
        [UINavigationBar appearance].standardAppearance = appearance;
        [UINavigationBar appearance].scrollEdgeAppearance = appearance;
}

2、添加代码
UIViewController+KMNavigationBarTransition.m
- (void)km_addTransitionNavigationBarIfNeeded中添加代码
bar.barTintColor = self.navigationController.navigationBar.barTintColor;
    if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *appearance = self.navigationController.navigationBar.standardAppearance;
        bar.standardAppearance = appearance;
        bar.scrollEdgeAppearance = appearance;
    } else {
        [bar setBackgroundImage:[self.navigationController.navigationBar backgroundImageForBarMetrics:UIBarMetricsDefault] forBarMetrics:UIBarMetricsDefault];
        bar.shadowImage = self.navigationController.navigationBar.shadowImage;
    }

3、使用
自定义UIViewController的title，self.navigationItem.titleView = ...

设置背景颜色：
if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *appearance = self.navigationController.navigationBar.standardAppearance;
        if (appearance) {
            appearance.backgroundImage = [UIImage imageWithColor:barTintColor];
        }
    } else {
        [self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:barTintColor] forBarPosition:UIBarPositionAny barMetrics:UIBarMetricsDefault];
    }

设置阴影：
if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *appearance = self.navigationController.navigationBar.standardAppearance;
        if (appearance) {
            appearance.shadowColor = nil;
            appearance.shadowImage = [UIImage getImageWithColor:lineColor andSize:CGSizeMake(1, 1)];
        }
    } else {
        [self.navigationController.navigationBar setShadowImage:[UIImage getImageWithColor:lineColor andSize:CGSizeMake(1, 1)]];
    }

**Comment by Weang** [comment]
我提交了一个pr来尝试解决这个问题，可以参考一下是否能够解决 #168

**Comment by slwhh** [comment]
还是有问题的，在 Example 工程看，返回之后当前页面的bar也被修改了。

**Comment by MoZhouqi** [comment]
The version 1.1.9 has added iOS 15 support.
