### ISSUE TITLE
为什么我在push里加了 设置控制器View.backgroundColor.. 导航栏设置颜色的方法都无效呢

### ISSUE THREAD

**Issue by ClegeJJ** [MoZhouqi/KMNavigationBarTransition#17]
![qq20160419-0 2x](https://cloud.githubusercontent.com/assets/13790283/14626897/27cdd4da-0622-11e6-9f14-4c8e3298d820.png)

如图所示：
重载了navigationController 的 push方法
在里面设置了被push的控制器的颜色
        // 设置控制器的View背景色
        viewController.view.backgroundColor = kColor_ViewBg;
导致 - > 在被push控制器里 设置导航栏颜色 无效......   
[self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:[UIColor redColor]] forBarMetrics:UIBarMetricsDefault];

我不知道这两句是不是有些联系... 但是我注释掉上面那句代码 导航栏颜色设置又好使了..

**Comment by MoZhouqi** [comment]
这句 `viewController.view.backgroundColor = kColor_ViewBg;` 改变了正常的初始化顺序，如果在 `viewDidLoad` 里设置导航栏背景样式的话，这个时候 `self.navigationController` 的值为 nil，所以其实并没有设置成功。

推荐把 `viewController.view.backgroundColor = kColor_ViewBg;` 放到别的地方，比如 `viewDidLoad` 里。

**Comment by ClegeJJ** [comment]
不用继承的话... 下面代码放到哪里合适呢~
 ```
viewController.view.backgroundColor = kColor_ViewBg;
```

**Comment by MoZhouqi** [comment]
放基类里应该是比较好的方案吧，可以用 Method Swizzling，但是不太推荐。
