### ISSUE TITLE
iOS15设置导航字体颜色 自动变为系统设置

### ISSUE THREAD

**Issue by zhaoqt521** [MoZhouqi/KMNavigationBarTransition#173]
![Kapture 2021-10-08 at 22 29 59](https://user-images.githubusercontent.com/16076705/136575186-84bfd554-7095-43f0-ad43-a31a4f54397a.gif)

**Comment by zedxpp** [comment]
因为现有的release最新版本是新创建的变量赋值的, 并且没有赋值你的这个属性, 直接指定git成最后一次提交的代码, 应该能行.
