### ISSUE TITLE
iOS15导航栏标题样式异常

### ISSUE THREAD

**Issue by GUIYIVIEW** [MoZhouqi/KMNavigationBarTransition#178]
https://user-images.githubusercontent.com/9626353/188072374-50a7fc79-1cc3-4f21-a984-748be9f4e9c3.MP4

A页面隐藏导航栏，跳转未隐藏导航栏的B页面，侧滑返回时，B页面导航标题字体样式会改变为A页面的默认值，松开手指则复原为自定义状态。

**Comment by MoZhouqi** [comment]
你好，本库目前是不管理标题的样式的
