### ISSUE TITLE
presentViewController 出一个NavigationController 会有些问题...

### ISSUE THREAD

**Issue by ClegeJJ** [MoZhouqi/KMNavigationBarTransition#18]
![71296364-05da-4cd0-86d6-716bf529a4c7](https://cloud.githubusercontent.com/assets/13790283/14637511/5824cf98-0664-11e6-8802-a6948af6df92.png)
![c51810be-eae2-4ca7-82ce-f7bcbcb3a128](https://cloud.githubusercontent.com/assets/13790283/14637524/739cb2ea-0664-11e6-91ce-460545dec9ec.png)
如上图所示

presentViewController 出导航控制器.. 导航控制器的RootViewController是 testViewController ,在testViewController的ViewDidLoad方法中 push到第二个控制器test2ViewController

效果如下图所示... 导航栏的背景色会闪现出来...在不导入框架的时候是正常的..不知道面对这样的需求 有什么办法弄好...
![default](https://cloud.githubusercontent.com/assets/13790283/14637606/0c0f731e-0665-11e6-8f05-4c9072730167.gif)

**Comment by ClegeJJ** [comment]
能做一个权限控制么? 让NavigationController不被框架影响...

**Comment by ClegeJJ** [comment]
![92c72731-c95c-4d49-8840-0c02869d754d](https://cloud.githubusercontent.com/assets/13790283/14638226/f80bcb0c-0668-11e6-874a-53a45da696eb.png)
类似写成这样子...

或者...代码上能解决这个问题

**Comment by MoZhouqi** [comment]
可以试试在 present 之前就设置好 navigation stack，代码如下：
```objective-c
navigationController.viewControllers = @[[JSBTestViewController new], [JSBTes2tViewController new]];
```

**Comment by ClegeJJ** [comment]
厉害！！佩服... 

想请教下~~ 你怎么知道...这样做就行了呢

**Comment by MoZhouqi** [comment]
直接设置 navigation stack 就不会调用到这个库的方法，但是看你贴的那几块代码应该也不会有问题，如果你有兴趣弄个 demo 的话我帮你仔细查下原因。

**Comment by ClegeJJ** [comment]
用你给的方法直接设置好了  demo可以的可以的~~

**Comment by ClegeJJ** [comment]
又出现了新的一个问题...真是麻烦作者了 
![simulator screen shot 2016 4 21 9 34 44](https://cloud.githubusercontent.com/assets/13790283/14695612/4a399f4c-07a6-11e6-84bd-2562188b5f13.png)
第一张页面 
```[self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:[UIColor yellowColor]] forBarMetrics:UIBarMetricsDefault];```
第二张页面
```[self.navigationController.navigationBar setBackgroundImage:nil forBarMetrics:UIBarMetricsDefault];```
为什么你的demo里push 的时候没有出现导航栏背景突变的情况呢

**Comment by MoZhouqi** [comment]
没有突变就对啦，这就是这个库的目的之一，使转场动画顺滑过渡。

**Comment by ClegeJJ** [comment]
!!!关键是~~~我是在导入你的库的情况下 还有这个背景突变的情况...

**Comment by MoZhouqi** [comment]
能弄个 demo 吗，我看看。

**Comment by ClegeJJ** [comment]
如果把你demo里面的tableview的背景色设置深一点颜色 也会有哦。。。
![Uploading 112.gif…]()

**Comment by ClegeJJ** [comment]
![112](https://cloud.githubusercontent.com/assets/13790283/14696607/22c25ef0-07af-11e6-8156-12888b267071.gif)

**Comment by MoZhouqi** [comment]
还是渐变呀。

**Comment by ClegeJJ** [comment]
能给个联系方式嘛。交流方便一点

**Comment by ClegeJJ** [comment]
作者大人在嘛...

**Comment by MoZhouqi** [comment]
你试试用代码改 backgroundColor。

**Comment by MoZhouqi** [comment]
你试试用代码设置背景色。

**Comment by MoZhouqi** [comment]
可以直接联系我 Gmail 邮箱。

**Comment by wyfhover** [comment]
所以，navigationbar背景突变的问题怎么解决
