### ISSUE TITLE
滑动切换的时候不起作用

### ISSUE THREAD

**Issue by smalldu** [MoZhouqi/KMNavigationBarTransition#19]
我的页面刚进去的时候navigationBar是透明的我用
```
self.navigationController?.navigationBar.setBackgroundImage(UIImage(), forBarMetrics: UIBarMetrics.Default)
self.navigationController?.navigationBar.shadowImage = UIImage()
```

然后随着滚动到一定的位置就改变为显示
```
self.navigationController?.navigationBar.setBackgroundImage(nil, forBarMetrics: UIBarMetrics.Default)
self.navigationController?.navigationBar.shadowImage = nil
```

但是不起作用，我移除这个库就有作用了，我轻轻的滑动返回一点然后继续停在这个页面，又可以其作用了。不知道为啥。麻烦看下

**Comment by MoZhouqi** [comment]
按照你上面的操作和描述，我觉得加不加我这个库的显示效果应该是一致的，所以不太容易定位到问题出在哪，你可以弄个 Demo 让我调试下吗？

**Comment by smalldu** [comment]
是加这个库引起的，因为我删了这个库就正常了   
我找到问题了 
  把这个方法（km_viewWillLayoutSubviews）注释掉 再把这个相关swizz注释掉 就OK了 
但是具体为什么 不清楚。。

**Comment by smalldu** [comment]
找到了  是这句话引起的 
self.km_prefersNavigationBarBackgroundViewHidden = YES;
注释掉就正常了

**Comment by MoZhouqi** [comment]
你能弄个 Demo 复现下这个问题吗？

**Comment by smalldu** [comment]
不好复现 ， 只有一个界面出现了。算了 关掉吧

**Comment by MoZhouqi** [comment]
跳转到这个页面前的转场操作是不是比较复杂，就是 push / pop 混合在一起？

你看看转场动画结束后这个 view controller 的 `viewDidAppear:` 调用了没，这个库 Swizzle 了 `viewDidAppear:` 并设置了 `self.km_prefersNavigationBarBackgroundViewHidden = NO;`

如果 `viewDidAppear:` 被调用了，那你在 `setKm_prefersNavigationBarBackgroundViewHidden:` 下个断点，看看 `viewDidAppear:` 被调用后有没有其他地方修改了这个属性的值。

**Comment by smalldu** [comment]
`viewDidAppear: `调用了，调用后没再执行`setKm_prefersNavigationBarBackgroundViewHidden:`

**Comment by MoZhouqi** [comment]
`viewDidAppear:` 里会把 `km_prefersNavigationBarBackgroundViewHidden` 的值设为 `NO`，理论上应该不会有问题。

**Comment by smalldu** [comment]
引入库出现这种情况
![引入库](http://upload-images.jianshu.io/upload_images/954071-5bd5102a69999930.gif?imageMogr2/auto-orient/strip)

注释掉那行
![注释掉](http://upload-images.jianshu.io/upload_images/954071-1d5866d98da3ef1c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

之后就正常了
![之后](http://upload-images.jianshu.io/upload_images/954071-ef94d35a46664bf1.gif?imageMogr2/auto-orient/strip)
