### ISSUE TITLE
当状态栏的样式为Black时，页面切换时会导致 navigationBar 的位置发生错误

### ISSUE THREAD

**Issue by sunbohong** [MoZhouqi/KMNavigationBarTransition#21]
测试代码见：https://github.com/MoZhouqi/KMNavigationBarTransition/pull/20

测试要点：将`navigationBar`设置为`black`，通过滑动手势轻轻滑动一下（不要`pop`到上一界面，而是停留在本界面），`navigationBar`的位置发生错误。

**Comment by MoZhouqi** [comment]
不用这个库也能复现，看上去应该是苹果的 bug。

**Comment by sunbohong** [comment]
@MoZhouqi  根据我自己的测试结果，这个bug看上去是苹果的。
这个issue的目的是，想知道通过 https://github.com/MoZhouqi/KMNavigationBarTransition  是否能够统一处理这种情况？

**Comment by MoZhouqi** [comment]
这个需要苹果去修复了。

**Comment by sunbohong** [comment]
@MoZhouqi  明白您的意思了。
