### ISSUE TITLE
为什么没有objective-c语言的Demo，看不懂Swift语言的代码

### ISSUE THREAD

**Issue by engebei** [MoZhouqi/KMNavigationBarTransition#23]

**Comment by MoZhouqi** [comment]
Hi，你可以参考[使用说明](https://github.com/MoZhouqi/KMNavigationBarTransition/blob/master/README_CN.md#使用说明)。

**Comment by engebei** [comment]
你好，[使用说明](https://github.com/MoZhouqi/KMNavigationBarTransition/blob/master/README_CN.md#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)也是没有objective-c语言的Demo的
