### ISSUE TITLE
how to set backitem title = ""

### ISSUE THREAD

**Issue by leancmscn** [MoZhouqi/KMNavigationBarTransition#24]

**Comment by MoZhouqi** [comment]
http://stackoverflow.com/questions/17403483/set-title-of-back-bar-button-item-in-ios

**Comment by leancmscn** [comment]
thanks.
like this:https://github.com/kingiol/KDInteractiveNavigationController
UINavigationController interactive with UINavigationBar hidden or show
Hide all UINavigationController backButtonItem's title, only show back arrow
