### ISSUE TITLE
这个库和SDAutoLayout、MJRefresh有冲突吗？

### ISSUE THREAD

**Issue by GanHuaLin** [MoZhouqi/KMNavigationBarTransition#27]
不知道是什么原因，用这个库后好多页面，布局位置有问题。
比如UIWebView用sdautolayout库布局然后再加上下拉刷新。
`self.webView.sd_layout
    .spaceToSuperView(UIEdgeInsetsMake(0, 0, 0, 0));
`

我在webview加载完成时调用
`[self.webView.scrollView setContentOffset:CGPointMake(0, 0) animated:NO];`
内容会在屏幕顶端（状态栏下方）

改成-64
`[self.webView.scrollView setContentOffset:CGPointMake(0, -64) animated:NO];`
这样就正常了。

还有其他一些页面也是出现类似问题，具体也不太好描述。

在StoryBoard里用autolayout方式布局也会不正常，
UIViewController里有个UIContainer包含了静态Cell  的 UITableView，
然后这个Tableview的上方也会空出一块区域。

**Comment by MoZhouqi** [comment]
你把这个库去了之后这些问题还存在吗？这个库应该不会影响当前的页面，只会在转场动画的时候做了一些处理。

**Comment by GanHuaLin** [comment]
哦，是的。不是这个库的问题。

**Comment by MoZhouqi** [comment]
应该把 `-64` 改成 `-scrollView.contentInset.top`，你可以看下 `automaticallyAdjustsScrollViewInsets` 这个属性的注释。
