### ISSUE TITLE
当导航栏颜色不变的时候，可以做到像系统那样的转场效果吗

### ISSUE THREAD

**Issue by wy19901227** [MoZhouqi/KMNavigationBarTransition#29]

**Comment by MoZhouqi** [comment]
本库为了转场动画效果的一致性，不会去做处理。

如果你希望达到这样的效果，可以判断两个转场 view controllers 的导航栏背景样式相关的属性设置是否一致，如果一致的话则不隐藏系统导航栏的 `backgroundView`。
