### ISSUE TITLE
set backtilte = "" not working 

### ISSUE THREAD

**Issue by leancmscn** [MoZhouqi/KMNavigationBarTransition#30]
let backbtn = UIBarButtonItem(title: "", style: .Plain, target: self, action: #selector(self.backBtnClicked))
        self.navigationController?.navigationBar.topItem?.backBarButtonItem = backbtn

sometimes not work

**Comment by MoZhouqi** [comment]
Hi, could you tell me how to reproduce the issue?

**Comment by JLCoffee** [comment]
侧滑时有晃动现象

**Comment by MoZhouqi** [comment]
@JLCoffee，可以具体描述下吗？

**Comment by JLCoffee** [comment]
就是不松手,手势来回滑动时,滑动界面边缘有晃动的情况

**Comment by MoZhouqi** [comment]
@JLCoffee 可以给个 Demo 复现下这个问题吗？
