### ISSUE TITLE
With added child view controller, animation can be broken

### ISSUE THREAD

**Issue by Igor-Palaguta** [MoZhouqi/KMNavigationBarTransition#31]
After adding child view controller navigation bar animation can be broken when switching from transparent bar to untransparent, and looks like this:
![withchildcontroller](https://cloud.githubusercontent.com/assets/800044/17666381/a683a776-6308-11e6-8033-7cadd4c51e2f.gif)

But expected this:
![withoutchildviewcontroller](https://cloud.githubusercontent.com/assets/800044/17666386/abbeacfe-6308-11e6-9649-4fdaec7e9884.gif)

The easiest way to replicate it add following code to your example:
```
   override func viewWillAppear(animated: Bool) {
      super.viewWillAppear(animated)
      navigationController?.setNavigationBarHidden(currentNavigationBarData.prefersHidden, animated: animated)

      dispatch_async(dispatch_get_main_queue()) {
         let child = UIViewController()
         child.view.hidden = true
         child.view.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
         child.view.frame = self.view.bounds
         self.view.addSubview(child.view)
         self.addChildViewController(child)
      }
   }
```

**Comment by MoZhouqi** [comment]
Hi, Thanks for your feedback.
You can try to call `addChildViewController:` before calling `addSubview:`.

**Comment by Igor-Palaguta** [comment]
Cool! Thank you! It works
