### ISSUE TITLE
在同一个navigationController里面某些viewController的push和pop想采用普通的效果，怎么破？

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MoZhouqi/KMNavigationBarTransition#32]
我发现用了大神你的这个项目，所有的navigationcontroller中的ViewController的push和pop操作效果都是你这个项目中所呈现的transition效果。我想在同一个navigationcontroller的栈中某些页面还是沿用系统的transition效果（push和pop的时候），某些有特殊需求的页面采用你这个项目中的transition效果，需要怎么破呢？

**Comment by MoZhouqi** [comment]
导航栏属性没有变化的转场动画效果是和系统的有些微差别，但是整个库的处理风格都很统一，个人认为还是挺美观的。

这个库的影响范围是全局的，并没有做开关，因为做这个库的初衷就是希望能够覆盖到所有的场景。

**Comment by jaybowong** [comment]
比较赞同 @TheWalkingDead1024 的想法，虽然我现在还没有遇到这种需求。

单独控制每个界面的样式应该是很多应用都避免不了的，毕竟需求千变万化不可预测。如果支持单个界面的话，灵活性更高，使用起来更方便一些。
支持单独开关感觉没有违背KMNavigationBarTransition的初衷，默认情况下覆盖了所有场景，特殊情况也能够特殊处理。
就像 [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) 一样，默认开启了之后，所有界面都不用担心键盘挡住输入框的问题了，但是仍然避免不了有些界面的需求很特殊，不得不自己做一些特别的额外的处理。

**Comment by MoZhouqi** [comment]
@TheWalkingDead1024 @jaybowong 感谢两位的回复，目前公司内部好几个 app 都用了这个库有一段时间了，没有发现不能解决的问题。如果你们在使用过程中发现了问题可以提 issue，如果真的很棘手没法解决，我会考虑加开关的。
