### ISSUE TITLE
底部1像素的黑线

### ISSUE THREAD

**Issue by bibuliu** [MoZhouqi/KMNavigationBarTransition#33]
你好，请问能提供支持定制Navibar底部1像素的线条颜色、隐藏的api吗。因为内部是新new一个navibar，所以自定义的设定在场景切换时会不起效。

**Comment by MoZhouqi** [comment]
`navigationBar.shadowImage = UIImage()` 这样就可以不显示那根一个像素的线了。

**Comment by bibuliu** [comment]
.抱歉，其实我更想知道的是能否更改颜色。

**Comment by MoZhouqi** [comment]
那你可以绘制一个像素高的图片，颜色设置成你想要的。
