### ISSUE TITLE
km_containerViewBackgroundColor adds white line during animation

### ISSUE THREAD

**Issue by Igor-Palaguta** [MoZhouqi/KMNavigationBarTransition#34]
Can we make km_containerViewBackgroundColor as associated property to allow users to customize background color. I have black controller and during custom animation appears white lines. Can prepare PR if needed

**Comment by MoZhouqi** [comment]
Hi, @Igor-Palaguta
As this pull request https://github.com/MoZhouqi/KMNavigationBarTransition/pull/6 mentioned, you can subclass UINavigationController and implement the `km_containerViewBackgroundColor` method in subclass to override the default color.

**Comment by Igor-Palaguta** [comment]
Thanks, for fast response!

Subclassing UINavigationController is not recommended.
I had to use following workaround for now:
   override func viewWillLayoutSubviews() {
      super.viewWillLayoutSubviews()

      if let tc = self.transitionCoordinator() {
         tc.containerView().backgroundColor = .blackColor()
      }
   }

**Comment by MoZhouqi** [comment]
Why is subclassing UINavigationController not recommended?

**Comment by Igor-Palaguta** [comment]
In old iOS versions it was denied to subclass UINavigationController and UITabBarController, but not it is fine. In any case not sure it is right way to subclass it just for one property. Easier to make it customizable in library

**Comment by MoZhouqi** [comment]
It is no problem to subclass UINavigationController in iOS 7 and later, and I don't think subclassing UINavigationController has side effects.
