### ISSUE TITLE
Pushing a view controller too soon after launch adds an extra UINavigationBar to the underlying view controller

### ISSUE THREAD

**Issue by inb4ohnoes** [MoZhouqi/KMNavigationBarTransition#35]
I'm opening my app from a push notification and immediately pushing a table view controller onto a navigation controller embedded in a tab bar controller right after launch. Doing so adds an extra navigation bar (it looks to be a copy of my own navigation bar) onto the underlying view controller's view, which also is a table view. Tabbing to another tab then tabbing back will get rid of the navigation bar. I am unable to provide screenshots or recordings publicly but if you need to see what i mean, please message me privately!

Edit: for now I've wrote some code to iterate through all the table view's subviews and remove UINavigationBar instances. It's a workaround but it seems to work. Would still love to see a solution to this!

**Comment by MoZhouqi** [comment]
Hi, @inb4ohnoes
Could you give me a demo and list the step by step process to reproduce the issue?
If it is not convenient for you to provide the recordings publicly, please feel free to email it to me.

**Comment by MoZhouqi** [comment]
Hi, @inb4ohnoes
Could you give me a demo and list the step by step process to reproduce the issue?
If it is not convenient for you to provide the recordings publicly, please feel free to email them to me.
