### ISSUE TITLE
Use only in specific cases

### ISSUE THREAD

**Issue by filipealva** [MoZhouqi/KMNavigationBarTransition#36]
I know it uses Method Swizzling, but there is no way to make it works only in specific cases?

For exemple, I have 2 occurrences in my app where the navigation bars are different, so your library is helping me a lot to achieve a nice transition between them.

But I would want to ensure that `KMNavigationBarTransition` only affects these two view controllers. 

There is a way to do that?

Thank you!

**Comment by MoZhouqi** [comment]
You can't do that currently, because the library affects global state.
