### ISSUE TITLE
导航栏颜色渐变问题

### ISSUE THREAD

**Issue by devxin** [MoZhouqi/KMNavigationBarTransition#38]
UITableView滚动获取alpha值，然后以一个颜色值来生成个图片设备UINaviagationBar背景色，当alpha值为1时，手滑滑动返回到一半，再放弃返回，会发现此界面ViewController的view向下偏了64

**Comment by MoZhouqi** [comment]
`KMNavigationBarTransition` 不会修改 view 的位置，这个应该是系统的行为。

**Comment by MoZhouqi** [comment]
`KMNavigationBarTransition` 不会修改 view 的位置，这个应该是系统的行为。你可以弄个 Demo 不，我查查原因。

**Comment by devxin** [comment]
新建了个Demo，发现并没有问题，可能是我们工程里重写了一些系统Delegate方法造成的

**Comment by MoZhouqi** [comment]
行，那我先把 issue 关了，如果有问题欢迎再提。
