### ISSUE TITLE
关于3D touch peek&pop的支持

### ISSUE THREAD

**Issue by rx2130** [MoZhouqi/KMNavigationBarTransition#39]
请问这个库支持3D touch peek&pop么？

比如现在从一个viewControllerA 往viewControllerB push，viewControllerB 里viewDidLoad我设置了它要透明的navigationBar。现在普通(单点)的push一切正常，但是如果3Dtouch 来push进入的话viewControllerB并不会透明navigatonBar :(

**Comment by MoZhouqi** [comment]
Hi, @rx2130 
感谢你的反馈。我刚试了下，`viewDidLod` 只有在 peek 的时候被调用，那个时候 `self.navigationController` 返回的是 nil，而 pop 的时候不会调用 `viewDidLod`，但是会调 `viewWillAppear:`。

所以如果需要支持 peek & pop，那可以在 `viewWillAppear:` 里设置导航栏的样式。
