### ISSUE TITLE
侧滑取消然后再侧滑会出现导航栏乱的现象

### ISSUE THREAD

**Issue by zhoujun951236** [MoZhouqi/KMNavigationBarTransition#42]
主页开启隐藏导航栏点击next到下一个界面选择bar tint color到第三层界面，第三层界面侧滑返回中途取消，然后再侧滑返回到上一层界面，再回到主页，关闭隐藏导航栏，点击next，就必现这个bug了。系统版本10以下都有这个问题，10以上的没有

**Comment by MoZhouqi** [comment]
应该是隐藏导航栏和系统边缘右滑返回手势一起使用触发了苹果的 bug。尽量避免连续两个页面隐藏导航栏，可以把导航栏背景色设置成透明的。
