### ISSUE TITLE
发现UI上有点问题

### ISSUE THREAD

**Issue by lyleLH** [MoZhouqi/KMNavigationBarTransition#44]
用手势慢慢pop的时候，发现当前界面的左侧边除去导航栏的部分有阴影，但是导航栏左边界部分没有阴影

**Comment by MoZhouqi** [comment]
Hi，能给个示例代码吗？

**Comment by lyleLH** [comment]
慢慢pop滑动的时候，上层界面的左边界是应该有阴影的，但是，目前导航栏底部以上的左边界区域没有阴影。http://ww4.sinaimg.cn/mw690/6de36fdcgw1fa0tmku6g3j208x0ggjsv.jpg

**Comment by lyleLH** [comment]
示例代码，我这边对导航栏没有多的设置，我猜想是不是因为首页的导航栏是白色，并且用 [naviBar setShadowImage:[[UIImage alloc] init]]; 设置隐藏了导航栏底部的线条，下一级界面是橙色，没有设置shadowImage导致的这个问题，所有导航栏的全局的translucent属性都是NO

**Comment by MoZhouqi** [comment]
`translucent` 为 `NO` 的时候系统会对导航栏区域做一些特殊处理，就会导致这样的问题。

**Comment by lyleLH** [comment]
translucent 的设置我修改过仍然存在这个问题。我不知道你能不能重现，我这里暂时没能解决它。

**Comment by MoZhouqi** [comment]
`translucent` 为 `YES` 的时候我试了下挺正常的。

**Comment by MakeBetterMe** [comment]
OC的能用么

**Comment by MoZhouqi** [comment]
@MakeBetterMe ObjC 和 Swift 都能用。
