### ISSUE TITLE
页面间NavigationBar透明与不透明之间切换的BUG

### ISSUE THREAD

**Issue by 393385724** [MoZhouqi/KMNavigationBarTransition#45]
iOS 10.0.1
我创建了三个ViewController，第一个不透明 第二个透明 第三个不透明
viewController1 -》 viewController2 -》 viewController3(此时ViewController2的navigation bar只显示44像素的颜色)
然后返回顺序
viewController3 -》viewController2 -》viewController1(此时ViewController1也只显示44像素)

**Comment by MoZhouqi** [comment]
透明指的是 `translucent` 属性吗？首先 `translucent` 设置好后最好就不要再改变，其次根据你的描述导航栏高度的变化应该是系统的行为。

**Comment by 393385724** [comment]
发现是我的问题，为了将底部的阴影线去掉我将navigationBar的clipsToBounds设置成YES了

**Comment by MoZhouqi** [comment]
`navigationController?.navigationBar.shadowImage = UIImage()` 这样就可以去除那根一像素的线了。

**Comment by 393385724** [comment]
是的，非常感谢你

**Comment by MoZhouqi** [comment]
不客气。 ：)
