### ISSUE TITLE
控制器里面有键盘弹出时

### ISSUE THREAD

**Issue by west-east** [MoZhouqi/KMNavigationBarTransition#46]
控制器里面有键盘弹出时，push操作反应会变慢（这个应该是系统的正常反应），但是手势pop回来时，侧边会出现闪烁情况。测试环境xcode8.1，模拟器8.0-10.0

**Comment by MoZhouqi** [comment]
Hi，你先把 `KMNavigationBarTransition` 去了看看是否还能复现，如果去了就没问题的话，麻烦提供个 demo 我来调试下。
