### ISSUE TITLE
Animation Issues

### ISSUE THREAD

**Issue by GardenerYun** [MoZhouqi/KMNavigationBarTransition#49]
KMNavigationBarTransition is amazing to manage the navigation bar styles and makes transition animations. but when i use push and (tabBarController) hidesBottomBarWhenPushed, navigation bar have a white line on the left.

**Comment by MoZhouqi** [comment]
Hi @GardenerYun, thanks for your feedback, but I can't reproduce the issue, so could you provide a demo?
