### ISSUE TITLE
用unwind Segue返回时，导航栏的转换延迟

### ISSUE THREAD

**Issue by speedpursuer** [MoZhouqi/KMNavigationBarTransition#50]
即使前后导航栏没有任何变化，回去时还是要有一个变白再显示的过程。猜测原因可以能是返回前一个view controller时后面那个view controller仍然存在所导致的。虽然可以用delegate作为workaround，但能支持就更方便，或者readme里面说明这个limit。

**Comment by MoZhouqi** [comment]
@speedpursuer 你好，我刚试了下用 unwind segue，看上去一切正常，并没有发现导航栏变白，你方便提供个 demo 吗？

**Comment by bernikowich-cedoni** [comment]
Hi guys, it's difficult to read this.)

**Comment by MoZhouqi** [comment]
Hi @bernikowich-cedoni, @speedpursuer said that the navigation bar transition is abnormal when using unwind segue, but I tried and found that everything is normal.
