### ISSUE TITLE
布局发生错乱

### ISSUE THREAD

**Issue by LoveSVN** [MoZhouqi/KMNavigationBarTransition#51]
navigationItem.hidesBackButton = true;
然后在第一页面显示navbar,第二页面显示时。改变不同改变statubar 颜色 会出现BUG

**Comment by MoZhouqi** [comment]
你好，根据描述感觉应该不是这个库引起的，你可以试试把库去了看还会发生页面布局错乱不？

**Comment by LoveSVN** [comment]
额，我是直接改的demo.

**Comment by LoveSVN** [comment]
只改变了状态栏文字颜色，快速的手势返回。同事 返回按钮 自定的。但是我返现跟自定义返回按钮没关系

**Comment by LoveSVN** [comment]
上一个界面状态栏界面和本界面状态栏文字颜色不一致

**Comment by MoZhouqi** [comment]
这个库并不会处理 status bar。
