### ISSUE TITLE
请问一下导入KMNavigationBarTransition，之后怎么全局修改返回按钮

### ISSUE THREAD

**Issue by KnightJoker** [MoZhouqi/KMNavigationBarTransition#52]
问题是这样的，我自己想全局自定义navigationbar 的返回按钮

自己采用的方法是在自定义的navigationController 里面重写 push 的方法

但是导入KMNavigationBarTransition 之后，应该是swizzling掉push方法

然后自己对Method Swizzling 并不是很了解，所以想请问一下po主

我想全局修改返回按钮为自定义按钮改怎么做呢？

**Comment by MoZhouqi** [comment]
用 Method Swizzling 面向切面编程就是为了不影响原有的逻辑，所以放心大胆地重写吧，只要别忘记调 super 方法就行。
