### ISSUE TITLE
NavigationBar changes colour if UITableViewController contains a UISearchController

### ISSUE THREAD

**Issue by Boobby69** [MoZhouqi/KMNavigationBarTransition#53]
The issue is that the navigationBar changes colour if UITableViewController contains a UISearchController.

Here is the code I use in viewDidLoad: 
`      let searchController = UISearchController(searchResultsController: nil)
        searchController.searchResultsUpdater = self
        searchController.delegate = self
        searchController.dimsBackgroundDuringPresentation = true
        searchBar.searchBarStyle = .prominent
        searchBar.sizeToFit()
        self.tableView.tableHeaderView = searchBar

        self.searchController = searchController
        definesPresentationContext = true
`

The issue occurs when I click on the search bar, then I cancel it. The navigation bar colour is then white.

**Comment by MoZhouqi** [comment]
Hi @Boobby69, thanks for your feedback, the issue has been fixed in 97309728e07e41f80ad8d41073834ce674c4a70c.
