### ISSUE TITLE
在导航栏上面设置图片的问题

### ISSUE THREAD

**Issue by Lshaoxun** [MoZhouqi/KMNavigationBarTransition#54]
我给导航栏设置一个底图，每次页面push和pop页面的时候导航栏的图片都是一开始显示拉伸的图片再显示正常的图片,设置底图的方法为在appdelegate中设置[[UINavigationBar appearance] setBackgroundImage:[UIImage imageNamed:@"navibg"] forBarMetrics:UIBarMetricsDefault];

**Comment by MoZhouqi** [comment]
你好，我试了下还挺正常的，能给个 demo 吗？

**Comment by Lshaoxun** [comment]
[KMNavigationBarTransition-master 2.zip](https://github.com/MoZhouqi/KMNavigationBarTransition/files/796330/KMNavigationBarTransition-master.2.zip)
点击next就会出现我说的那种情况

**Comment by MoZhouqi** [comment]
你好 @Lshaoxun，我试了下是导航栏的 translucent 发生了变化，但是图片并没有被拉伸。

**Comment by Lshaoxun** [comment]
谢谢
