### ISSUE TITLE
oc 里面隐藏导航栏之后其他页面全部都隐藏了

### ISSUE THREAD

**Issue by ryanypm** [MoZhouqi/KMNavigationBarTransition#60]
![image](https://cloud.githubusercontent.com/assets/7519919/23506844/38c8843a-ff85-11e6-88b8-9246bb449395.png)

![image](https://cloud.githubusercontent.com/assets/7519919/23507095/610c7266-ff86-11e6-8b20-5b430a890f23.png)

返回去不见了
![image](https://cloud.githubusercontent.com/assets/7519919/23507082/552699f4-ff86-11e6-809e-f3c7650a82fb.png)

必须要写
viewWillDisappear

**Comment by MoZhouqi** [comment]
是的，这个库只会处理背景色，导航栏的显隐需要自己去设置，你可以参考 Demo。
