### ISSUE TITLE
Navigation bar appearance breaks under stress situations

### ISSUE THREAD

**Issue by rogerluan** [MoZhouqi/KMNavigationBarTransition#61]
Hello

I've been trying to make this work for awhile, but I can't seem to find the root cause of this bug.

We have a tab bar controller with some tabs, and if I go to each tab and starts flashing the screens (pressing all the tabs rapidly one at a time), the navigation bar breaks whenever I try to use it afterward (like pushing a new VC into the stack).

That happens if I am normally using the app, apparently randomly, since I couldn't find the root cause of this bug.

Has this happened before? I tried reproducing in the example project (adding a tab bar to it and trying to cause a stress situation) but I couldn't reproduce it there.

Also, I am loading nav bar's properties on each view controller's viewDidAppear - does this sound right?

Thank you for this library, it's just amazing.

Looking forward to find a fix this bug :)

**Comment by tinpont** [comment]
Please try to set NavigationBar barTintColor, backgroundImage, shadowImage only in `viewDidLoad` function. You should only care about current viewController's navigationBar style.

If you still have same problem, please offer an example project.

**Comment by rogerluan** [comment]
I fixed the issue! The problem was that a specific view controller was using the UINavigationBar appearance proxy, so it was causing that weird behavior randomly. Simply deleted that line and it stopped glitching!

I'm still loading every nav bar property in viewDidAppear because I'm loading all the nav bar settings at once using a helper class and the titleColor property misbehaves if called only from viewDidLoad (when popping/pushing to/from different view controllers).

Hope this solution helps someone.

Thanks!
