### ISSUE TITLE
Navigation bar's right part flashes when push to a view controller.

### ISSUE THREAD

**Issue by jaybowong** [MoZhouqi/KMNavigationBarTransition#62]
Version 0.0.10 doesn't have this problem.

![ezgif-3-e0421c60b0](https://cloud.githubusercontent.com/assets/1948533/23655401/ced54c0e-036f-11e7-8bf2-23a82d0202b6.gif)

**Comment by MoZhouqi** [comment]
I'm so sorry, I checked out the recent commits and found that only this commit https://github.com/MoZhouqi/KMNavigationBarTransition/commit/97309728e07e41f80ad8d41073834ce674c4a70c may affect the transitions, so could you try to revert this commit to see if it can fix the issue.

**Comment by jaybowong** [comment]
@MoZhouqi 
Yes, reverting 9730972 solved it.

**Comment by MoZhouqi** [comment]
Hi @jaybowong, could you find the cause of the problem?

**Comment by gabutdinov** [comment]
Reverting not helped for me, i still have this flashing

**Comment by MoZhouqi** [comment]
Hi @gabutdinov, does version 0.0.10 have this problem?

**Comment by gabutdinov** [comment]
Hi @MoZhouqi . Yes 0.0.10 has this too. I set navigation bar's `translucent` to `true` only for one viewcontroller, then I set it to `false`. And navigation bar flashes in next viewcontrollers even if I use `setBackgroundImage` to set navigation bar's color.

**Comment by MoZhouqi** [comment]
Hi @gabutdinov, it is not recommend to change the value of the `translucent` property after initialization which has been mentioned in README.

**Comment by Igor-Palaguta** [comment]
Same issue appeared after migrating to 1.0.0 version

**Comment by unkosun** [comment]
我有一个同样的 bug，但是我调用的是setViewControllers:animated:

**Comment by MoZhouqi** [comment]
I reproduced the issue recently and it has been fixed in 1970e90997346a29a4be86374df192cb46cc1aa0, sorry for the late resolution.

**Comment by MoZhouqi** [comment]
I reproduced the issue recently and it has been fixed in 8727b2d, sorry for the late resolution.
