### ISSUE TITLE
method_exchangeImplementations会影响苹果审核么

### ISSUE THREAD

**Issue by jiao808813** [MoZhouqi/KMNavigationBarTransition#63]
#import "KMSwizzle.h"
#import <objc/runtime.h>

void KMSwizzleMethod(Class cls, SEL originalSelector, SEL swizzledSelector)
{
    Method originalMethod = class_getInstanceMethod(cls, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(cls, swizzledSelector);
    
    BOOL didAddMethod =
    class_addMethod(cls,
                    originalSelector,
                    method_getImplementation(swizzledMethod),
                    method_getTypeEncoding(swizzledMethod));
    
    if (didAddMethod) {
        class_replaceMethod(cls,
                            swizzledSelector,
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }
}

包含了method_exchangeImplementations方法

**Comment by MoZhouqi** [comment]
不会影响审核，目前也没有被拒的案例，可以放心使用。
