### ISSUE TITLE
导航栏黑线问题

### ISSUE THREAD

**Issue by zycLuke** [MoZhouqi/KMNavigationBarTransition#66]
隐藏导航栏黑线后，push一个控制器，线条出现然后马上消失。

**Comment by MoZhouqi** [comment]
你好，可以提供个 demo 来复现这个问题吗？

**Comment by boyssimple** [comment]
处理了么 @zycLuke

**Comment by MoZhouqi** [comment]
Example 里的是正常的。@zycLuke @boyssimple

**Comment by zycLuke** [comment]
@MoZhouqi  问题解决了， 是我自己的问题，抱歉迟来的答复。   @boyssimple 我不大清楚你是什么问题

**Comment by boyssimple** [comment]
你那边是什么造 成的
 
 
------------------ Original ------------------

**Comment by zycLuke** [comment]
@boyssimple 我这边需要把导航栏黑线隐藏掉，我之前的做法是层层递归找到导航栏的线隐藏，会发生这个问题。现在用
`[self.navigationBar setBackgroundImage:[[UIImage alloc] init] forBarMetrics:UIBarMetricsDefault];
    self.navigationBar.shadowImage = [[UIImage alloc] init];`
这样就没问题了

**Comment by boyssimple** [comment]
我就是这样去隐藏背景的
 
 
------------------ Original ------------------

**Comment by zycLuke** [comment]
@boyssimple 我是写在自己定义统一的UINavigationController类中viewDidLoad里，问题就解决了
