### ISSUE TITLE
how to hide all back button title?

### ISSUE THREAD

**Issue by longxianlin** [MoZhouqi/KMNavigationBarTransition#68]

**Comment by MoZhouqi** [comment]
Hi @longxianlin, please use Google to find out the answer.

**Comment by Pratik948** [comment]
@longxianlin you can check out [my category](https://github.com/The10Men/Category/tree/master/UINavigationController%2BHideBackTitle) with zero config to hide back button title. (Zero config inspired by [KMNavigationBarTransition](https://github.com/MoZhouqi/KMNavigationBarTransition))
