### ISSUE TITLE
iOS 11 Compatibility

### ISSUE THREAD

**Issue by inb4ohnoes** [MoZhouqi/KMNavigationBarTransition#69]
It seems that in the first iOS 11 beta, there were some major changes to UINavigationBars and how they worked. This results in some weird behavior after pushing view controllers...

**Comment by MoZhouqi** [comment]
Could you try it on the iOS device directly?

**Comment by inb4ohnoes** [comment]
Yes I have tried it. There seems to be layout issues and visual glitches. Namely There is a layout issue going from vc with nav bar -(push)-> vc with no nav bar where the top content inset on the vc still shows there is a nav bar but the nav bar is actually not there. There is also visual glitches pushing between standard vcs with standard navbars. That's all I've seen so far.

**Comment by sablib** [comment]
pop
![img_f2f7cb2e42b1-1](https://user-images.githubusercontent.com/3134048/27416416-f13431c4-573f-11e7-855a-e90166e153d0.jpeg)

push
![img_c6b06a5c8a7b-1](https://user-images.githubusercontent.com/3134048/27416419-f3b66944-573f-11e7-9e05-e71a65188b7f.jpeg)

**Comment by bramkerstenmedia** [comment]
Does anyone have a fix for this problem? This library is great so I want to use it.

**Comment by sablib** [comment]
@bramkerstenmedia 
I have a naive fix at https://github.com/sablib/KMNavigationBarTransition/tree/fix_ios_11

**Comment by Pratik948** [comment]
@sablib Unfortunatly it didn't work for me!!

**Comment by MoZhouqi** [comment]
I already have a solution and will fix the issue later.

**Comment by MoZhouqi** [comment]
iOS 11 has been supported.

**Comment by Pratik948** [comment]
@MoZhouqi (After the new commit) I noticed that (even in the example) background of navigation bar shifts off a little bit when navigation bar's translucent property set to false. you can refer to screenshot below. This happens also when pushing to next view controller
![img_0367](https://user-images.githubusercontent.com/18482201/30643242-c123deb6-9e2b-11e7-95d3-d2c8115d5bbf.png)

**Comment by MoZhouqi** [comment]
@Pratik948 Yes, you can open a new issue.
