### ISSUE TITLE
Bug when pushing new view controller from viewDidLoad()

### ISSUE THREAD

**Issue by NosovPavel** [MoZhouqi/KMNavigationBarTransition#73]
When you are trying to push another (let it be №2) view controller from viewDidLoad() (№1) everything looks good before you want to pop back. NavigationBar inside view controller №1 will be transparent.

**Comment by MoZhouqi** [comment]
Hi @NosovPavel, it is not recommend to push a new view controller in `viewDidLoad` method.

**Comment by NosovPavel** [comment]
@MoZhouqi Yeah, but what should I do in this case? If I push new VC in viewWillAppear or later user will see the content and if I do it in viewDidLoad user won't see content. I need this behavior because of project requirements, main thing is - user should have opportunity to move back to rootVC.

**Comment by MoZhouqi** [comment]
You could try to use the `setViewControllers:` method.
