### ISSUE TITLE
侧滑 偶尔出现UI卡死

### ISSUE THREAD

**Issue by zznfly** [MoZhouqi/KMNavigationBarTransition#78]
侧滑 偶尔出现UI卡死，点击home 键后，再打开恢复正常，就是push到下个页面时卡死。 不知道是不是跟我 设置 导航栏的手势的方式 有关

**Comment by wukongzhikong** [comment]
同样出现了楼上描述的问题

**Comment by MoZhouqi** [comment]
@zznfly @wukongzhikong，这个是系统的 bug，在 demo 的 `NavigationController.swift` 文件里有处理的方法。
