### ISSUE TITLE
iOS11转场动画问题

### ISSUE THREAD

**Issue by zhangMax** [MoZhouqi/KMNavigationBarTransition#79]
如下图用setBackgroundImage: forBarMetrics:方法设置了导航栏背景图片，但在push和pop时会出现下图这种情况，不知道是为什么。

![Uploading Simulator Screen Shot - iPhone 7 - 2017-09-01 at 13.49.04.png…]()

**Comment by zhangMax** [comment]
图片上传失败。。您可以在iOS11的环境运行下demo，也存在一样的问题，希望能适配一下，谢谢！

**Comment by nikans** [comment]
I can confirm: 
![simulator_screen_shot_-_iphone_7__11_0__-_2017-09-04_at_15_40_12](https://user-images.githubusercontent.com/1039100/30027121-3ba468f0-9188-11e7-9612-bc20b02f6996.png)
![simulator_screen_shot_-_iphone_7__11_0__-_2017-09-04_at_15_40_27](https://user-images.githubusercontent.com/1039100/30027123-3bcb1c52-9188-11e7-8412-17921f062e29.png)
![simulator_screen_shot_-_iphone_7__11_0__-_2017-09-04_at_15_40_32](https://user-images.githubusercontent.com/1039100/30027124-3bd13e84-9188-11e7-99af-fe9c1b57122b.png)

**Comment by shengyangyu** [comment]
确实有问题，顶一个。

**Comment by cuzv** [comment]
因为系统在 push 和 pop 的时候会去设置 _backgroundView 的 hidden 值为 false 造成 hacking 失效了 ==。

**Comment by MoZhouqi** [comment]
已经有解决方案了，等别人的 pr 合并后，我再修改下就能适配 iOS 11 啦。

**Comment by MoZhouqi** [comment]
iOS 11 has been supported.

**Comment by nikans** [comment]
You should probably add a release, right?
