### ISSUE TITLE
UINavigationBar tintColor support.

### ISSUE THREAD

**Issue by jaybowong** [MoZhouqi/KMNavigationBarTransition#8]
It's better to support `navigationBar.tintColor`.

In most cases the tint color changes along with the bar tint color.
A light tint color looks good with a dark bar tint color, but looks bad when push to a light-bar-tint-color view controller.
Really hope you could think about it.

I'm not familiar with method swizzling things. Maybe I can try it myself later.
Thanks so much. You're amazing!

**Comment by MoZhouqi** [comment]
Yes, you are right, but the library is not suitable for dealing with this situation. You could change the tint color of the navigation bar in `viewWillAppear:` if necessary. 

Thank you for your appreciation, @jaybowong!

**Comment by MoZhouqi** [comment]
Hi, you could use custom view with different color to fix the problem.
