### ISSUE TITLE
Xcode9 iOS11 scrollVIew新加adjustedContentInset替换contentInset

### ISSUE THREAD

**Issue by shengyangyu** [MoZhouqi/KMNavigationBarTransition#80]
Xcode9 iOS11 scrollVIew新加adjustedContentInset替换contentInset修复，已创建分支：https://github.com/shengyangyu/KMNavigationBarTransition

**Comment by zhangMax** [comment]
push的时候还是有问题，应该是这个方法计算错误了km_resizeTransitionNavigationBarFrame

**Comment by MoZhouqi** [comment]
你好，我已经在 pr 下面回复了，这个 issue 就先关闭了。
