### ISSUE TITLE
iOS 11 Support shifts off background of navigation bar

### ISSUE THREAD

**Issue by Pratik948** [MoZhouqi/KMNavigationBarTransition#83]
As mentioned in issue https://github.com/MoZhouqi/KMNavigationBarTransition/issues/69 navigation bar background shifts off (i guess the side of status bar). 
It happens when performing push, pop or interactive pop.
P.S.> this behaviour is only occurs when navigation bar's translucent property is set to false
Screenshot:
![img_0367](https://user-images.githubusercontent.com/18482201/30645829-8dddee94-9e34-11e7-8036-53cb053708d0.png)

**Comment by MoZhouqi** [comment]
Hi @Pratik948, it seems a system's bug, if you remove the library in the example, so magic will be happened.

**Comment by Pratik948** [comment]
@MoZhouqi well, i'm not on my mac now, I will check it if the same thing happens without the library!!!

**Comment by Pratik948** [comment]
It seems like this happens when the view controller contains a subclass of scrollview or a scrollview. I've tested it without a scrollview(UITableView) this issued doesn't seem to appear. If anyone finds the root cause for this issue please correct me if i'm wrong.

**Comment by xclidongbo** [comment]
Me too. How can I update the newest version?

**Comment by LuochuanAD** [comment]
<img width="370" alt="537ab5e5-1713-4e44-9666-2c75b24f9c6a" src="https://user-images.githubusercontent.com/19641279/30838861-aaf4bc5e-a2a0-11e7-814c-5747127617fc.png">
bug:当pushViewController:时,tabbar会向上偏移. 但是当popToViewController:时,tabbar显示正常.

**Comment by sseen** [comment]
This issue is not case by the scrollview, or not just, I found this always happen when u set the navigation bar  translucent  false, I tried the newest Example in KMNavigationNarTransition , the same result.

**Comment by MoZhouqi** [comment]
The issue has been fixed in release 1.1.0.
