### ISSUE TITLE
ios11下 有一个bug

### ISSUE THREAD

**Issue by tangguoan** [MoZhouqi/KMNavigationBarTransition#89]
在push控制器的时,在下一个控制器将要出现时,导航栏bar下面会有一条宽影!

**Comment by tangguoan** [comment]
[http://rjtx-dev.oss-cn-beijing.aliyuncs.com/ceshi/Untitled.gif](url)

**Comment by SimleCp** [comment]
我也是碰到这个问题了. 我看作者提交过几次iOS11的支持, 但是cocoapods没有更新.

**Comment by fdyhgjg** [comment]
pod 'KMNavigationBarTransition', :git => 'https://github.com/MoZhouqi/KMNavigationBarTransition.git'

**Comment by wooden1985** [comment]
fdyhgjg 正解

**Comment by MoZhouqi** [comment]
1.1.0 版本已经适配了 iOS 11 并且提交到 CocoaPods 了。
