### ISSUE TITLE
导航栏的title有三个点，viewDidLoad无法获取传值

### ISSUE THREAD

**Issue by allanzhang** [MoZhouqi/KMNavigationBarTransition#9]
如题，滑动发挥时候，导航栏title上有三个蓝点，用了这个库，所有的界面传值viewDidLoad拿不到，都是nil，viewWillAppear可以拿到，什么情况

**Comment by MoZhouqi** [comment]
三个蓝点的问题你可以搜索下解决方案，还有你可以把我的库先去掉看看是不是还有同样的问题。
