### ISSUE TITLE
push时，tabbar上移好像是在phoneX上运行就会出现

### ISSUE THREAD

**Issue by fdyhgjg** [MoZhouqi/KMNavigationBarTransition#90]
push时候 tabbar会向上移动一段距离 好像并不是ios11系统问题 我拿6sp（ios11系统）手机运行工程 push不会出现。拿phoneX模拟器运行 push就会出现向上移动。
有个小猜测：1，可能是模拟器bug    2，phoneX中safeAreaInsets这个属性是不是在搞鬼的原因 
https://www.lee1994.com/guan-yu-iphone/ 这里有个适配phoneX的小简介。希望楼主能把这个解决掉

**Comment by MoZhouqi** [comment]
试试 release 1.1.0

**Comment by fdyhgjg** [comment]
好的 现在就去试试。刺激。楼主就是给力

**Comment by MoZhouqi** [comment]
哈哈哈，楼主不是你吗= =

**Comment by fdyhgjg** [comment]
你才是楼主。  我试了 版本1.1.1。push在phoneX上 tabbar还是会上移动。。。

**Comment by MoZhouqi** [comment]
能给个 demo 吗，我调试下。

**Comment by fdyhgjg** [comment]
就是xcode9。用phoneX模拟器跑的。 就一个UITabBarController里面装nav。作push动作。 你拿xcode9的phoneX模拟器试试。是tabbar上移动。不是navBar

**Comment by MoZhouqi** [comment]
我用项目工程里的 Example 试了下，没有复现额。

**Comment by fdyhgjg** [comment]
......不是吧。我这就是系统的导航栏和tabbar 自己没定义。你那里竟然没问题

**Comment by MoZhouqi** [comment]
是呀，我试了木有问题。

**Comment by d553296416** [comment]
测了下系统的tabbar会上移

**Comment by fdyhgjg** [comment]
上移的问题。自己可以解决了
-(void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated{
    
    if (self.viewControllers.count) {
        viewController.hidesBottomBarWhenPushed = YES;
        
        // 定义leftBarButtonItem
        viewController.navigationItem.leftBarButtonItem = [UIBarButtonItem itemWithTargat:self action:@selector(back) image:@"icon_nav_return" highImage:nil];
    }
    
    [super pushViewController:viewController animated:animated];
    
    // 修改tabBra的frame
    CGRect frame = self.tabBarController.tabBar.frame;
    frame.origin.y = [UIScreen mainScreen].bounds.size.height - frame.size.height;
    self.tabBarController.tabBar.frame = frame;
}
在BaseNavigationController重写push动画方法 手动赋值坐标就好了

**Comment by MoZhouqi** [comment]
我设置了`hidesBottomBarWhenPushed` 这个属性后复现了， 不过看起来是系统的问题。

**Comment by fdyhgjg** [comment]
总算你是复现了。     确实好像是系统问题。  好了。 这个算是可以继续用了。很完美。 比起之前自己自定义导航栏 还是这个简单点，方便用些。

**Comment by MoZhouqi** [comment]
我设置了 `hidesBottomBarWhenPushed` 属性后在 iPhone X 模拟器上复现了，不过看起来是系统的问题。

**Comment by MoZhouqi** [comment]
@fdyhgjg 哈哈，谢谢反馈，不知道 iPhone X 的真机会不会有这个问题。

**Comment by fdyhgjg** [comment]
@MoZhouqi   坐等真机测试 -。- 反正暂时是强行解决了。。。。

**Comment by DarrenKong** [comment]
@fdyhgjg 你这样处理也有问题。pop的时候，TabBar的height会变小。最好的处理是自定义TabBar，参考https://stackoverflow.com/questions/46232929/why-page-push-animation-tabbar-moving-up-in-the-iphone-x
