### ISSUE TITLE
遇到一个颜色push 后 背景色不显示的问题

### ISSUE THREAD

**Issue by czboosj** [MoZhouqi/KMNavigationBarTransition#92]
自定义的UINavigationBar add 在controller view 上面,但是用了这个库发现 在ios 11 上push 后背景色不见了,变成白色

**Comment by MoZhouqi** [comment]
能给个 demo 吗？

**Comment by MusicOnMyMind** [comment]
![8980229b-9cfb-4c08-bffe-e48e2d760c54](https://user-images.githubusercontent.com/16969590/32882232-a5eb5f8a-caee-11e7-86cb-5fa7abfe5387.png)
我是在Present一个黑色半透明的导航栏控制器(导航不显示)，Push的时候发现背景色会被改成白色，后面这里改成Clean就可以。

**Comment by MoZhouqi** [comment]
感谢 @MusicOnMyMind，这个 issue 我先关闭了。
