### ISSUE TITLE
IOS11 navigationBar height changes when push

### ISSUE THREAD

**Issue by Liqiankun** [MoZhouqi/KMNavigationBarTransition#99]
![navigationbar](https://user-images.githubusercontent.com/11532418/31883916-1386fe20-b81e-11e7-9e5a-bb685855bb67.gif)

**Comment by MoZhouqi** [comment]
Hi @Liqiankun, what is the version of the repo?

**Comment by Liqiankun** [comment]
Sorry, I forgot! I will try the latest version. See if it fixed this issue. Then I will let you know!

**Comment by hziKen** [comment]
hi,are you solve your problem?

**Comment by hziKen** [comment]
can u tell me how to fix it?

**Comment by Liqiankun** [comment]
@hziKen Update KMNavigationBarTransition to the the latest version.

**Comment by Liqiankun** [comment]
@MoZhouqi The latest version does not have this issue

**Comment by hziKen** [comment]
I HAD UPDATE IT ,BUT STILL CAN NOT SOLVE MY ISSUE

**Comment by hziKen** [comment]
the latest version is 1.0.0?

**Comment by CeceXX** [comment]
The latest version is 1.1.5.

**Comment by Liqiankun** [comment]
@hziKen Fixed it?

**Comment by CeceXX** [comment]
I can confirm that this issue was tested in the latest release.

**Comment by CeceXX** [comment]
*fixed

**Comment by Liqiankun** [comment]
@CeceXX Good
